project:
  type: website

website:
  title: "Guía de Cactus"
  navbar:
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Especies"
        file: especies.qmd
      - text: "Acerca"
        file: acerca.qmd
format:
  html:
    theme: cosmo
    toc: true
